/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ArbitrageVault } from "./ArbitrageVault";
export type { BurraNFT } from "./BurraNFT";
export type { GhoToken } from "./GhoToken";
export type { PriceConsumerV3 } from "./PriceConsumerV3";
